# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - azure-strapi-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://nikhilstrapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c27cd3517a7412784256921ee1fc797 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0fcee6ed7cac4bbe835527a8a1375d93 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nikhilstrapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c27cd3517a7412784256921ee1fc797 }}/strapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azure-strapi-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fcf74865e07e4bc596f755d094038d4e }}
        images: 'nikhilstrapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c27cd3517a7412784256921ee1fc797 }}/strapi:${{ github.sha }}'